### ISSUE TITLE
Importing workflow. (Initial state of jobs)

### ISSUE THREAD

**Issue by TiSiE** [yawik/StackoverflowApi#6]
The initial status of imported jobs by a crawler must be configurable.

Currently they are imported as "Created", meaning the administrator has to approve every single job...

For some crawler this might not be the desired behaviour. So it must be possible to set the inital state per crawler.

If not possible in a fair amount of effort - set the initial state to "Active".

**Comment by fedys** [comment]
I am going to implement "initial job state per crawler" approach. This task should be placed in https://github.com/yawik/SimpleImport/issues or not?

**Comment by TiSiE** [comment]
Of course, it should!
Shame over me for the rest of my life.....

I created the issue in the RIGHT place: yawik/SimpleImport#1
