### ISSUE TITLE
Newly added crawler did not run.

### ISSUE THREAD

**Issue by TiSiE** [yawik/StackoverflowApi#7]
After adding a crawler and then start the import process, this crawler does not run. 

1. A newly added crawler must immediatley be runnable.
2. The time period, in which the crawler is considered "already run" must be configurable.
    (for each crawler preferably, or at least globally)

**Comment by fedys** [comment]
Fixed via https://github.com/yawik/SimpleImport/commit/8753ded747fadb440657f97c78b0491480a9f26e
The time period was already globally configurable via `SimpleImport\Options\ModuleOptions::$importRunDelay`. I am going to make a per crawler configuration.

**Comment by TiSiE** [comment]
I just realized that this is the complete wrong repository for this issue, but you figured it out already....

New issue is here: yawik/SimpleImport#2
